POST http://localhost:4000/register 
Content-Type: application/json

{
    "name":"ramesh",
    "email":"man@abc", 
    "age":"25", 
    "mobile":2547889, 
    "work":"dev", 
    "add":"hyd",
    "desc":"hello"
    
    
} 

###
GET http://localhost:4000/getdata 

### 
GET http://localhost:4000/getuser/6411d5114b76e2aa9c034548 
